CREATE TABLE IF NOT EXISTS developer(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,skills TEXT, fecha TEXT, img TEXT, img2 TEXT, img3 TEXT, email TEXT);

CREATE TABLE IF NOT EXISTS comment(id INTEGER PRIMARY KEY AUTOINCREMENT, msg TEXT, email TEXT, avatar TEXT, img TEXT, postId INTEGER);